#!/bin/bash

echo "install depends..."
pip3 install PyUserInput pyautogui pexpect configparser pyperclip

echo "install dogtail..."
cd /usr/share/dsystem/dogtail/ && python3 setup.py install

gsettings set org.gnome.desktop.interface toolkit-accessibility true

for I in /home/*; do
	THISUSER=`echo $I | cut -d "/" -f 3 -`
	USERID=`id -u $THISUSER 2>/dev/null || echo "_FALSE_"`
	if [ $USERID = '_FALSE_' -o $THISUSER != "deepin" ] ; then
		continue
	fi

	grep "$THISUSER  ALL=(ALL) NOPASSWD:ALL" /etc/sudoers
	if [ $? != 0 ] ; then
		echo "$THISUSER  ALL=(ALL) NOPASSWD:ALL" >>/etc/sudoers
	fi
done

cat >/usr/bin/dsystem<<EOF
#!/bin/bash
cd /usr/share/dsystem/dsystem && python3 rr_test.py --run_launcher=True --run_dock=True
EOF
chmod +x /usr/bin/dsystem

id deepin
if [ $? -eq 0 ] ; then
	chown deepin:deepin /usr/share/dsystem -R
fi

grep "export NO_AT_BRIDGE=1" /etc/environment
if [ $? != 0 ] ; then
	echo "export NO_AT_BRIDGE=1" >> /etc/environment
fi
